//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="CompassIncomingWebServiceImplPortBinding", Namespace="http://host.wm6.swisslog.com/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(messageResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hostOrderLine))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(messageRequest))]
public interface ICompassIncomingWebServiceImplPortBinding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://host.wm6.swisslog.com/", ResponseNamespace="http://host.wm6.swisslog.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("orderMasterMessageResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    cpOrderMasterMessageResponse orderMaster([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] cpOrderMasterMessageRequest orderMasterMessageRequest);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class cpOrderMasterMessageRequest : messageRequest {
    
    private hostOrderGroup orderGroupField;
    
    private cpHostOrder[] orderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostOrderGroup orderGroup {
        get {
            return this.orderGroupField;
        }
        set {
            this.orderGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public cpHostOrder[] order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostOrderGroup {
    
    private string orderGroupIdField;
    
    private System.DateTime dispatchDateField;
    
    private int priorityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderGroupId {
        get {
            return this.orderGroupIdField;
        }
        set {
            this.orderGroupIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dispatchDate {
        get {
            return this.dispatchDateField;
        }
        set {
            this.dispatchDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class messageError {
    
    private int codeField;
    
    private bool codeFieldSpecified;
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool codeSpecified {
        get {
            return this.codeFieldSpecified;
        }
        set {
            this.codeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cpOrderMasterMessageResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class messageResponse {
    
    private messageHeader messageHeaderField;
    
    private messageError messageErrorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public messageHeader messageHeader {
        get {
            return this.messageHeaderField;
        }
        set {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public messageError messageError {
        get {
            return this.messageErrorField;
        }
        set {
            this.messageErrorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class messageHeader {
    
    private string msgIdField;
    
    private string msgTypeField;
    
    private string transCodeField;
    
    private System.DateTime msgTimeField;
    
    private bool msgTimeFieldSpecified;
    
    private string senderField;
    
    private string receiverField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string msgId {
        get {
            return this.msgIdField;
        }
        set {
            this.msgIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string msgType {
        get {
            return this.msgTypeField;
        }
        set {
            this.msgTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string transCode {
        get {
            return this.transCodeField;
        }
        set {
            this.transCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime msgTime {
        get {
            return this.msgTimeField;
        }
        set {
            this.msgTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool msgTimeSpecified {
        get {
            return this.msgTimeFieldSpecified;
        }
        set {
            this.msgTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string receiver {
        get {
            return this.receiverField;
        }
        set {
            this.receiverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class cpOrderMasterMessageResponse : messageResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostAttributeValue {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cpHostOrderLine))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostOrderLine {
    
    private int orderLineNumberField;
    
    private string orderedTuIdField;
    
    private string productIdField;
    
    private string productVersionIdField;
    
    private string displayPickUomIdField;
    
    private string minUomRoundingRuleField;
    
    private string minUomIdField;
    
    private double quantityOrderedField;
    
    private int expirationWindowField;
    
    private bool expirationWindowFieldSpecified;
    
    private int allocationToleranceWindowField;
    
    private bool allocationToleranceWindowFieldSpecified;
    
    private int fifoCutOffToleranceField;
    
    private bool fifoCutOffToleranceFieldSpecified;
    
    private hostAttributeValue[] attributeValueField;
    
    private hostInstruction[] instructionField;
    
    private string loadBuildingEpisodeField;
    
    private string loadBuldingGroupField;
    
    private string loadBuildingRelatedEpisodeField;
    
    private string loadBuildingDisjointEpisodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int orderLineNumber {
        get {
            return this.orderLineNumberField;
        }
        set {
            this.orderLineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderedTuId {
        get {
            return this.orderedTuIdField;
        }
        set {
            this.orderedTuIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productId {
        get {
            return this.productIdField;
        }
        set {
            this.productIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productVersionId {
        get {
            return this.productVersionIdField;
        }
        set {
            this.productVersionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string displayPickUomId {
        get {
            return this.displayPickUomIdField;
        }
        set {
            this.displayPickUomIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string minUomRoundingRule {
        get {
            return this.minUomRoundingRuleField;
        }
        set {
            this.minUomRoundingRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string minUomId {
        get {
            return this.minUomIdField;
        }
        set {
            this.minUomIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double quantityOrdered {
        get {
            return this.quantityOrderedField;
        }
        set {
            this.quantityOrderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int expirationWindow {
        get {
            return this.expirationWindowField;
        }
        set {
            this.expirationWindowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expirationWindowSpecified {
        get {
            return this.expirationWindowFieldSpecified;
        }
        set {
            this.expirationWindowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int allocationToleranceWindow {
        get {
            return this.allocationToleranceWindowField;
        }
        set {
            this.allocationToleranceWindowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool allocationToleranceWindowSpecified {
        get {
            return this.allocationToleranceWindowFieldSpecified;
        }
        set {
            this.allocationToleranceWindowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int fifoCutOffTolerance {
        get {
            return this.fifoCutOffToleranceField;
        }
        set {
            this.fifoCutOffToleranceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fifoCutOffToleranceSpecified {
        get {
            return this.fifoCutOffToleranceFieldSpecified;
        }
        set {
            this.fifoCutOffToleranceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributeValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostAttributeValue[] attributeValue {
        get {
            return this.attributeValueField;
        }
        set {
            this.attributeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("instruction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostInstruction[] instruction {
        get {
            return this.instructionField;
        }
        set {
            this.instructionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string loadBuildingEpisode {
        get {
            return this.loadBuildingEpisodeField;
        }
        set {
            this.loadBuildingEpisodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string loadBuldingGroup {
        get {
            return this.loadBuldingGroupField;
        }
        set {
            this.loadBuldingGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string loadBuildingRelatedEpisode {
        get {
            return this.loadBuildingRelatedEpisodeField;
        }
        set {
            this.loadBuildingRelatedEpisodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string loadBuildingDisjointEpisode {
        get {
            return this.loadBuildingDisjointEpisodeField;
        }
        set {
            this.loadBuildingDisjointEpisodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostInstruction {
    
    private string textField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class cpHostOrderLine : hostOrderLine {
    
    private string productDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productDescription {
        get {
            return this.productDescriptionField;
        }
        set {
            this.productDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostShipment {
    
    private string shipmentIdField;
    
    private System.DateTime shippingDateField;
    
    private string truckIdField;
    
    private string sealingTagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipmentId {
        get {
            return this.shipmentIdField;
        }
        set {
            this.shipmentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime shippingDate {
        get {
            return this.shippingDateField;
        }
        set {
            this.shippingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string truckId {
        get {
            return this.truckIdField;
        }
        set {
            this.truckIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sealingTag {
        get {
            return this.sealingTagField;
        }
        set {
            this.sealingTagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostAddress {
    
    private string contactPersonField;
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string addressLine3Field;
    
    private string cityField;
    
    private string stateField;
    
    private string postalCodeField;
    
    private string countryField;
    
    private string phoneNumber1Field;
    
    private string phoneNumber2Field;
    
    private string phoneNumber3Field;
    
    private string email1Field;
    
    private string email2Field;
    
    private string email3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contactPerson {
        get {
            return this.contactPersonField;
        }
        set {
            this.contactPersonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressLine3 {
        get {
            return this.addressLine3Field;
        }
        set {
            this.addressLine3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneNumber1 {
        get {
            return this.phoneNumber1Field;
        }
        set {
            this.phoneNumber1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneNumber2 {
        get {
            return this.phoneNumber2Field;
        }
        set {
            this.phoneNumber2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneNumber3 {
        get {
            return this.phoneNumber3Field;
        }
        set {
            this.phoneNumber3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email1 {
        get {
            return this.email1Field;
        }
        set {
            this.email1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email2 {
        get {
            return this.email2Field;
        }
        set {
            this.email2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email3 {
        get {
            return this.email3Field;
        }
        set {
            this.email3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class hostOrderAddress {
    
    private string addressIdField;
    
    private hostAddress addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressId {
        get {
            return this.addressIdField;
        }
        set {
            this.addressIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostAddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public partial class cpHostOrder {
    
    private string carrierField;
    
    private string orderIdField;
    
    private string orderTypeField;
    
    private System.DateTime dispatchDateField;
    
    private System.DateTime orderDateField;
    
    private bool orderDateFieldSpecified;
    
    private int priorityField;
    
    private string customerField;
    
    private hostOrderAddress shippingAddressField;
    
    private hostOrderAddress billingAddressField;
    
    private string workstationField;
    
    private string consolidationLocField;
    
    private string orderTuTypeField;
    
    private string ownerField;
    
    private bool shortAllocationAllowedField;
    
    private bool shortAllocationAllowedFieldSpecified;
    
    private bool shortReleasingAllowedField;
    
    private bool shortReleasingAllowedFieldSpecified;
    
    private bool shortShippingAllowedField;
    
    private bool shortShippingAllowedFieldSpecified;
    
    private bool automaticAllocationAllowedField;
    
    private bool automaticAllocationAllowedFieldSpecified;
    
    private int stopSequenceField;
    
    private bool stopSequenceFieldSpecified;
    
    private hostShipment shipmentField;
    
    private string[] capabilityField;
    
    private hostInstruction[] instructionField;
    
    private cpHostOrderLine[] orderLineField;
    
    private string sandwichPalletField;
    
    private int minOrderTUsField;
    
    private bool minOrderTUsFieldSpecified;
    
    private int maxOrderTUsField;
    
    private bool maxOrderTUsFieldSpecified;
    
    private int wrapperProgramField;
    
    private bool wrapperProgramFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderType {
        get {
            return this.orderTypeField;
        }
        set {
            this.orderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dispatchDate {
        get {
            return this.dispatchDateField;
        }
        set {
            this.dispatchDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime orderDate {
        get {
            return this.orderDateField;
        }
        set {
            this.orderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderDateSpecified {
        get {
            return this.orderDateFieldSpecified;
        }
        set {
            this.orderDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostOrderAddress shippingAddress {
        get {
            return this.shippingAddressField;
        }
        set {
            this.shippingAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostOrderAddress billingAddress {
        get {
            return this.billingAddressField;
        }
        set {
            this.billingAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string workstation {
        get {
            return this.workstationField;
        }
        set {
            this.workstationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string consolidationLoc {
        get {
            return this.consolidationLocField;
        }
        set {
            this.consolidationLocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderTuType {
        get {
            return this.orderTuTypeField;
        }
        set {
            this.orderTuTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool shortAllocationAllowed {
        get {
            return this.shortAllocationAllowedField;
        }
        set {
            this.shortAllocationAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool shortAllocationAllowedSpecified {
        get {
            return this.shortAllocationAllowedFieldSpecified;
        }
        set {
            this.shortAllocationAllowedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool shortReleasingAllowed {
        get {
            return this.shortReleasingAllowedField;
        }
        set {
            this.shortReleasingAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool shortReleasingAllowedSpecified {
        get {
            return this.shortReleasingAllowedFieldSpecified;
        }
        set {
            this.shortReleasingAllowedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool shortShippingAllowed {
        get {
            return this.shortShippingAllowedField;
        }
        set {
            this.shortShippingAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool shortShippingAllowedSpecified {
        get {
            return this.shortShippingAllowedFieldSpecified;
        }
        set {
            this.shortShippingAllowedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool automaticAllocationAllowed {
        get {
            return this.automaticAllocationAllowedField;
        }
        set {
            this.automaticAllocationAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool automaticAllocationAllowedSpecified {
        get {
            return this.automaticAllocationAllowedFieldSpecified;
        }
        set {
            this.automaticAllocationAllowedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int stopSequence {
        get {
            return this.stopSequenceField;
        }
        set {
            this.stopSequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stopSequenceSpecified {
        get {
            return this.stopSequenceFieldSpecified;
        }
        set {
            this.stopSequenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostShipment shipment {
        get {
            return this.shipmentField;
        }
        set {
            this.shipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("capability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] capability {
        get {
            return this.capabilityField;
        }
        set {
            this.capabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("instruction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public hostInstruction[] instruction {
        get {
            return this.instructionField;
        }
        set {
            this.instructionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("orderLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public cpHostOrderLine[] orderLine {
        get {
            return this.orderLineField;
        }
        set {
            this.orderLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sandwichPallet {
        get {
            return this.sandwichPalletField;
        }
        set {
            this.sandwichPalletField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int minOrderTUs {
        get {
            return this.minOrderTUsField;
        }
        set {
            this.minOrderTUsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minOrderTUsSpecified {
        get {
            return this.minOrderTUsFieldSpecified;
        }
        set {
            this.minOrderTUsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxOrderTUs {
        get {
            return this.maxOrderTUsField;
        }
        set {
            this.maxOrderTUsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxOrderTUsSpecified {
        get {
            return this.maxOrderTUsFieldSpecified;
        }
        set {
            this.maxOrderTUsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int wrapperProgram {
        get {
            return this.wrapperProgramField;
        }
        set {
            this.wrapperProgramField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool wrapperProgramSpecified {
        get {
            return this.wrapperProgramFieldSpecified;
        }
        set {
            this.wrapperProgramFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cpOrderMasterMessageRequest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://host.wm6.swisslog.com/")]
public abstract partial class messageRequest {
    
    private messageHeader messageHeaderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public messageHeader messageHeader {
        get {
            return this.messageHeaderField;
        }
        set {
            this.messageHeaderField = value;
        }
    }
}
